### ISSUE TITLE
Blurring downloaded image

### ISSUE THREAD

**Issue by ksy5662** [PomepuyN/BlurEffectForAndroidDesign#4]
Dear PomepuyN,

Thanks for your great sample!!

I am trying to add picasso image loader to download any image from flickr.
But seems it is not working with picasso.

Picasso.with(this.getApplicationContext()).load("http://farm8.staticflickr.com/7195/6980356584_874a4e6346_z.jpg").into(mNormalImage);

Better to share any sample to blurring downloade images.

Happy New Year!!

**Comment by kwent** [comment]
Duplicate with https://github.com/PomepuyN/BlurEffectForAndroidDesign/issues/5
